# exp setting
exp_name: 'ptrcos512'
ckpt_path: 'lightning_logs/ptrcos512/epoch=136-val/brier_fde=3.30.ckpt'
# ckpt_path: null
seed: 42
debug: False
devices: [0]

# common
model_name: ptr
num_modes: 6
hidden_size: 128
num_encoder_layers: 2
num_decoder_layers: 2
tx_hidden_size: 384
tx_num_heads: 16
dropout: 0.1
entropy_weight: 40.0
kl_weight: 20.0
use_FDEADE_aux_loss: True

# train
max_epochs: 200
learning_rate: 0.001 
optimizer: AdamW
scheduler: cosine 
ewc_lambda: 2000
train_batch_size: 512
eval_batch_size: 1024 
grad_clip_norm: 5

# data related
load_num_workers: 8
train_data_path: ["data/dlav_data/train"]
# val_data_path: ["data/dlav_data/val"]
val_data_path: ["data/dlav_data/test_easy"]
max_data_num: [1000000]
max_num_agents: 15
map_range: 100
max_num_roads: 256
max_points_per_lane: 20 
manually_split_lane: False
point_sampled_interval: 1
num_points_each_polyline: 20
vector_break_dist_thresh: 1.0
